[package]
name = "anti-mvi"
version = "0.1.0"
edition = "2021"

[dependencies]
egui = "0.28.1"
reactive-rs = "0.1.1"

[dependencies.tokio]
version = "1.39.3"
features = ["macros", "rt"]

[dependencies.uuid]
version = "1.10.0"
features = ["v4", "fast-rng"]
